# Generated by Django 4.1 on 2024-03-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
