# Generated by Django 4.1 on 2024-03-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_company_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency_symbol',
            field=models.TextField(blank=True, default='₹'),
        ),
    ]
