# Generated by Django 4.1 on 2024-03-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_company_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
