# Generated by Django 4.1 on 2024-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_cart_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='landmark',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='India', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='order_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
