# Generated by Django 4.1 on 2024-03-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_address_line_1_useraddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
