# Generated by Django 4.1 on 2024-03-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discounted_price',
        ),
    ]
