# Generated by Django 4.1 on 2024-03-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_banner_heading_banner_sub_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_best_selling',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_new_arrival',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
